# YOUR NAME: 参加者のID
service: hands-on-<YOUR NAME>

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  # LambdaのRoleを設定
  role: <ROLE>
  # role: arn:aws:iam::xxxxxxxxxx:role/xxxxxxxxxx

functions:
  # hello関数
  hello:
    handler: hello.handler

  # リダイレクト関数
  redirect:
    # handler: redirect.handler
    handler: redirect2.handler # 応用問題はこちらを利用
    events:
      - http:
          path: redirect
          method: get
          integration: lambda

# 応用問題で利用
resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        # Table名を設定
        TableName: <YOUR TABLE NAME>
